src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PatientRepository::class)
 */
class Patient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Person::class, inversedBy="person", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Person;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Adress;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_At;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $created_by;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPerson(): ?Person
    {
        return $this->Person;
    }

    public function setPerson(Person $Person): self
    {
        $this->Person = $Person;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(?string $Adress): self
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(?\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(?string $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

src/Form/PatientType.php
<?php

namespace App\Form;

use App\Entity\Patient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PatientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Adress')
            //->add('created_At')
            //->add('created_by')
            ->add('picture')
            //->add('Person')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Patient::class,
        ]);
    }
}

src/Controller/PatientController.php
<?php

namespace App\Controller;

use App\Entity\Patient;
use App\Form\PatientType;
use App\Repository\PatientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/patient')]
class PatientController extends AbstractController
{
    #[Route('/', name: 'patient_index', methods: ['GET'])]
    public function index(PatientRepository $patientRepository): Response
    {
        $this->denyAccessUnlessGranted("ROLE_MEDECIN", null, "User tried to access patient list with access right");
        return $this->render('patient/index.html.twig', [
            'patients' => $patientRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'patient_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $patient = new Patient();
        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($patient);
            $entityManager->flush();

            return $this->redirectToRoute('patient_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('patient/new.html.twig', [
            'patient' => $patient,
            'form' => $form,
        ]);
    }



    #[Route('/{id}', name: 'patient_show', methods: ['GET'])]
    public function show(Patient $patient): Response
    {

        return $this->render('patient/show.html.twig', [
            'patient' => $patient,
        ]);
    }

    #[Route('/{id}/edit', name: 'patient_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Patient $patient): Response
    {
        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('patient_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('patient/edit.html.twig', [
            'patient' => $patient,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'patient_delete', methods: ['POST'])]
    public function delete(Request $request, Patient $patient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$patient->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($patient);
            $entityManager->flush();
        }

        return $this->redirectToRoute('patient_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/patient/_delete_form.html.twig
<form method="post" action="{{ path('patient_delete', {'id': patient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ patient.id) }}">
    <button class="btn">Delete</button>
</form>

templates/patient/edit.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Edit Patient{% endblock %}

{% block body %}
    <h1>Modifier Les Informations du patient</h1>

    {{ include('patient/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('patient_index') }}">back to list</a>

    {{ include('patient/_delete_form.html.twig') }}
{% endblock %}

templates/patient/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Patient index{% endblock %}

{% block body %}
    <h1>Patient index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Adress</th>
                <th>Created_At</th>
                <th>Created_by</th>
                <th>Picture</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for patient in patients %}
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.Adress }}</td>
                <td>{{ patient.createdAt ? patient.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ patient.createdBy }}</td>
                <td>{{ patient.picture }}</td>
                <td>
                    <a href="{{ path('patient_show', {'id': patient.id}) }}">show</a>
                    <a href="{{ path('patient_edit', {'id': patient.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>



{% endblock %}

templates/patient/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Patient{% endblock %}

{% block body %}
    <h1>Create new Patient</h1>

    {{ include('patient/_form.html.twig') }}

    <a href="{{ path('patient_index') }}">back to list</a>
{% endblock %}

templates/patient/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patient{% endblock %}

{% block body %}
    <h1>Patient</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ patient.id }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ patient.Adress }}</td>
            </tr>
            <tr>
                <th>Created_At</th>
                <td>{{ patient.createdAt ? patient.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Created_by</th>
                <td>{{ patient.createdBy }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ patient.picture }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('patient_index') }}">back to list</a>

    <a href="{{ path('patient_edit', {'id': patient.id}) }}">edit</a>

    {{ include('patient/_delete_form.html.twig') }}
{% endblock %}