src/Entity/Doctor.php
<?php

namespace App\Entity;

use App\Repository\DoctorRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DoctorRepository::class)
 */
class Doctor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $Matricule;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profilePicture;

    /**
     * @ORM\OneToOne(targetEntity=Person::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Person;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $created_by;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_At;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(?string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->Person;
    }

    public function setPerson(Person $Person): self
    {
        $this->Person = $Person;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(?string $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(?\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }
}

src/Entity/Hopital.php
<?php

namespace App\Entity;

use App\Repository\HopitalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HopitalRepository::class)
 */
class Hopital
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomHopital;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $NoUrgence;


    /**
     * @ORM\OneToOne(targetEntity=Person::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Person;


    public function __construct()
    {
        $this->serviceHopitals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomHopital(): ?string
    {
        return $this->NomHopital;
    }

    public function setNomHopital(string $NomHopital): self
    {
        $this->NomHopital = $NomHopital;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(?string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getNoUrgence(): ?string
    {
        return $this->NoUrgence;
    }

    public function setNoUrgence(?string $NoUrgence): self
    {
        $this->NoUrgence = $NoUrgence;

        return $this;
    }





    public function getPerson(): ?Person
    {
        return $this->Person;
    }

    public function setPerson(Person $Person): self
    {
        $this->Person = $Person;

        return $this;
    }

}

src/Entity/MedecinServiceHopital.php
<?php

namespace App\Entity;

use App\Repository\MedecinServiceHopitalRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MedecinServiceHopitalRepository::class)
 */
class MedecinServiceHopital
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $createBy;

    /**
     * @ORM\ManyToOne(targetEntity=Doctor::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $medecin;

    /**
     * @ORM\ManyToOne(targetEntity=ServiceHopital::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $ServiceHopital;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreateBy(): ?string
    {
        return $this->createBy;
    }

    public function setCreateBy(?string $createBy): self
    {
        $this->createBy = $createBy;

        return $this;
    }

    public function getMedecin(): ?Doctor
    {
        return $this->medecin;
    }

    public function setMedecin(?Doctor $medecin): self
    {
        $this->medecin = $medecin;

        return $this;
    }

    public function getServiceHopital(): ?ServiceHopital
    {
        return $this->ServiceHopital;
    }

    public function setServiceHopital(?ServiceHopital $ServiceHopital): self
    {
        $this->ServiceHopital = $ServiceHopital;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomService;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $createdBy;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;


    public function __construct()
    {
        $this->serviceHopitals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomService(): ?string
    {
        return $this->NomService;
    }

    public function setNomService(string $NomService): self
    {
        $this->NomService = $NomService;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?string $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToOne(targetEntity=Person::class, mappedBy="UserPerson", cascade={"persist", "remove"})
     */
    private $person;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $created_by;


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(Person $person): self
    {
        // set the owning side of the relation if necessary
        if ($person->getUserPerson() !== $this) {
            $person->setUserPerson($this);
        }

        $this->person = $person;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(?string $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

}

src/Form/MedecinServiceHopitalType.php
<?php

namespace App\Form;

use App\Entity\MedecinServiceHopital;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MedecinServiceHopitalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('createdAt')
            ->add('createBy')
            ->add('status')
            ->add('medecin')
            ->add('ServiceHopital')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MedecinServiceHopital::class,
        ]);
    }
}

src/Controller/MedecinServiceHopitalController.php
<?php

namespace App\Controller;

use App\Entity\MedecinServiceHopital;
use App\Form\MedecinServiceHopitalType;
use App\Repository\DoctorRepository;
use App\Repository\MedecinServiceHopitalRepository;
use App\Repository\ServiceHopitalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/medecin_service_hopital')]
class MedecinServiceHopitalController extends AbstractController
{
    #[Route('/', name: 'medecin_service_hopital_index', methods: ['GET'])]
    public function index(MedecinServiceHopitalRepository $medecinServiceHopitalRepository): Response
    {
        return $this->render('medecin_service_hopital/index.html.twig', [
            'medecin_service_hopitals' => $medecinServiceHopitalRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'medecin_service_hopital_new', methods: ['GET','POST'])]
    public function new(Request $request, DoctorRepository $doctorRepository, ServiceHopitalRepository $serviceHopitalRepository): Response
    {
        $medecinServiceHopital = new MedecinServiceHopital();

        $medecins = $doctorRepository->findAll();
        $servicehops = $serviceHopitalRepository->findAll();
        if($request->isMethod("POST")){
            if($this->isCsrfTokenValid('csrf_token', $request->request->get('csrf_token'))){
                $serviceHop = $serviceHopitalRepository->find($request->request->get('serviceHopID'));
                $medecin = $doctorRepository->find($request->request->get('medecinID'));
                $medecinServiceHopital->setServiceHopital($serviceHop);
                $medecinServiceHopital->setMedecin($medecin);
                $medecinServiceHopital->setStatus('active');
                $medecinServiceHopital->setCreatedAt(new \DateTimeImmutable());
                $medecinServiceHopital->setCreateBy($this->getUser()->getUserIdentifier());
                $this->getDoctrine()->getManager()->persist($medecinServiceHopital);
                $this->getDoctrine()->getManager()->flush();
            }
        }

        return $this->render('medecin_service_hopital/new.html.twig', [
            'medecins'=>$medecins,
            'servicehops'=>$servicehops
        ]);
    }

    #[Route('/{id}', name: 'medecin_service_hopital_show', methods: ['GET'])]
    public function show(MedecinServiceHopital $medecinServiceHopital): Response
    {
        return $this->render('medecin_service_hopital/show.html.twig', [
            'medecin_service_hopital' => $medecinServiceHopital,
        ]);
    }

    #[Route('/{id}/edit', name: 'medecin_service_hopital_edit', methods: ['GET','POST'])]
    public function edit(Request $request, MedecinServiceHopital $medecinServiceHopital): Response
    {
        $form = $this->createForm(MedecinServiceHopitalType::class, $medecinServiceHopital);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('medecin_service_hopital_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('medecin_service_hopital/edit.html.twig', [
            'medecin_service_hopital' => $medecinServiceHopital,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'medecin_service_hopital_delete', methods: ['POST'])]
    public function delete(Request $request, MedecinServiceHopital $medecinServiceHopital): Response
    {
        if ($this->isCsrfTokenValid('delete'.$medecinServiceHopital->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($medecinServiceHopital);
            $entityManager->flush();
        }

        return $this->redirectToRoute('medecin_service_hopital_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/medecin_service_hopital/_delete_form.html.twig
<form method="post" action="{{ path('medecin_service_hopital_delete', {'id': medecin_service_hopital.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medecin_service_hopital.id) }}">
    <button class="btn">Delete</button>
</form>

templates/medecin_service_hopital/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MedecinServiceHopital{% endblock %}

{% block body %}
    <h1>Edit MedecinServiceHopital</h1>

    {{ include('medecin_service_hopital/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('medecin_service_hopital_index') }}">back to list</a>

    {{ include('medecin_service_hopital/_delete_form.html.twig') }}
{% endblock %}

templates/medecin_service_hopital/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}MedecinServiceHopital index{% endblock %}

{% block body %}
    <h1>Medecins Et Spécialités</h1>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom Medecin</th>
                <th>Matricule</th>
                <th>Hopital</th>
                <th>Service</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% set i = 0 %}
        {% for medecin_service_hopital in medecin_service_hopitals %}
            {% set i = i + 1 %}
            <tr>
                <td>{{ i }}</td>
                <td>{{ medecin_service_hopital.Medecin.Person.nomPostnom | capitalize }}</td>
                <td>{{ medecin_service_hopital.Medecin.matricule | upper }}</td>
                <td>{{ medecin_service_hopital.ServiceHopital.Hopital.nomHopital | capitalize }}</td>
                <td>{{ medecin_service_hopital.ServiceHopital.Service.nomService | capitalize }}</td>
                <td>
                    <a href="{{ path('medecin_service_hopital_show', {'id': medecin_service_hopital.id}) }}">show</a>
                    <a href="{{ path('medecin_service_hopital_edit', {'id': medecin_service_hopital.id}) }}">edit</a>
                    <a class="btnCreateRelation" id="{{ medecin_service_hopital.id }}" href="#!" role="button">Choisir</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('medecin_service_hopital_new') }}">Create new</a>
    <script src="{{ asset("assets/js/jquery.min.js") }}"></script>
    <script>
        $(document).ready(function(e){
            $(".btnCreateRelation").on('click', function(e){
                let patientID = {{ app.user.id }}
                    console.log(patientID)
                let medecinID = $(this).attr("id")
                console.log(medecinID)
                if(patientID != "" && medecinID != ""){
                    $.ajax({
                        type: "POST",
                        url: "/choix_medecin/createRelationToDoctorJson",
                        data: {
                            medecinID: medecinID,
                            patientID: patientID
                        },
                        dataType: "json",
                        success: function(response) {
                            console.log(response);
                        }
                    })
                }

            })

        })
    </script>
{% endblock %}

templates/medecin_service_hopital/new.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}New MedecinServiceHopital{% endblock %}

{% block body %}
    <h1>Affecter un médecin à un service</h1>

    <form class="form-sample" method="post">

        <div class="row">
            <div class="col-md-4">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Hopital</label>

                    <input type="hidden" value="{{ csrf_token('csrf_token') }}" name="csrf_token">
                    <div class="col-sm-9">
                        <select name="medecinID" class="form-control" id="">
                            {% for doctor in medecins %}
                                <option value="{{ doctor.id }}">{{ doctor.Person.nomPostnom | upper ~" | " ~ doctor.matricule | upper }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Service</label>
                    <div class="col-sm-9">
                        <select name="serviceHopID" class="form-control" id="">
                            {% for service in servicehops %}
                                <option value="{{ service.id }}">{{ service.Service.nomService | capitalize ~ " | "~ service.Hopital.nomHopital }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group row">
                    <input type="submit" class="btn btn-primary btn-sm" value="Enregistrer">
                </div>
            </div>
        </div>

    </form>
    <a href="{{ path('medecin_service_hopital_index') }}">back to list</a>
{% endblock %}

templates/medecin_service_hopital/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MedecinServiceHopital{% endblock %}

{% block body %}
    <h1>MedecinServiceHopital</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ medecin_service_hopital.id }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ medecin_service_hopital.createdAt ? medecin_service_hopital.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>CreateBy</th>
                <td>{{ medecin_service_hopital.createBy }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ medecin_service_hopital.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('medecin_service_hopital_index') }}">back to list</a>

    <a href="{{ path('medecin_service_hopital_edit', {'id': medecin_service_hopital.id}) }}">edit</a>

    {{ include('medecin_service_hopital/_delete_form.html.twig') }}
{% endblock %}